<template>
  <div class="flex flex-col h-screen">
    <header class="flex bg-black">
      <div class="flex w-9/12 ml-auto mr-auto">
        <h1 class="flex flex-col content-center justify-center pt-4 pb-4 text-xl font-bold text-white font-text">
          Open Regulation Platform API
        </h1>
        <p class="flex flex-col content-center justify-center pl-2 pr-2 mt-auto mb-auto ml-4 text-lg font-bold tracking-widest text-white h-1/3 font-text bg-primary">
          Alpha
        </p>
      </div>
    </header>

    <div class="w-11/12 pt-12 ml-auto mr-auto border-t-8 border-solid md:w-9/12 md:flex border-primary">
      <aside class="pl-8 pr-8 md:sticky md:top-0 md:w-2/12 md:pl-0 md:pr-0">
        <div class="mb-6">
          <h1 class="mb-6 text-xl font-bold text-link">Get Started</h1>
          <a class="block mb-4 text-link" href="#introduction">Introduction</a>
          <a class="block mb-4 text-link" href="#authentication">Authentication</a>
          <a class="block mb-4 text-link" href="#searching">Searching</a>
          <a class="block mb-4 text-link" href="#graph_searching">Graph Search</a>
          <a class="block mb-4 text-link" href="#enrichment">Enrichments</a>
          <a class="block mb-4 text-link" href="#subscriptions">Subscriptions</a>
        </div>

        <div class="mb-6">
          <h1 class="mb-6 text-xl font-bold text-link">Resources</h1>
          <a class="block mb-4 text-link" href="#document">Document</a>
          <a class="block mb-4 text-link" href="#taxonomy">Taxonomy</a>
          <a class="block mb-4 text-link" href="#entity">Entity</a>
        </div>
      </aside>

      <div class="md:w-10/12">
        <div class="lg:flex">
          <div class="pl-8 pr-8">
            <h1 id="introduction" class="mb-8 text-xl font-bold">Introduction</h1>
            <p class="mb-4 text-lg text-primary">
              The Open Regulation Platform (ORP) seeks to enable regulatory innovation by publishing UK 
              legislation and regulation as open machine-readable data. The key policy aim is to promote the use of
              emerging technologies and of regulation as data.
            </p>

            <p class="mb-4 text-gray-600 ">
              The project will publish UK primary and secondary legislation and
              regulatory guidance as machine-readable data, developing an accurate dataset of
              the real-world regulatory obligations faced by business.  This will be enriched with metadata generated by
              semantic analysis using Natural Language Processing techniques, which will add greater insights than the raw
              text alone. For example, we will be able to classify legislation by industry and geography and cluster similar
              legislation together.
            </p>

            <p class="mb-4 text-gray-600 ">
              The ORP will transform how organisations understand and comply with regulation and improve the
              transparency of government by publishing requirements on business in a systematic and consistent form.
            </p>

          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- Authentication -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold" id="authentication">Authentication</h1>
            <p class="mb-4 text-lg text-primary">
              The Open Regulation Platform API uses bearer tokens as the method of authentication.
            </p>

            <p class="mb-4 text-gray-600">
              To retrieve a bearer token, send a
              <code class="p-1 text-sm text-link bg-secondary">POST</code> request to <code class="p-1 text-sm text-link bg-secondary">/auth/login/</code>
              with the username and password provided to you. Please note that this token will expire after one hour.
            </p>

            <p class="mb-4 text-gray-600">
              To use the token, add it to the header of subsequent requests with the format
              <code class="p-1 text-sm text-link bg-secondary">Authorization: Bearer {signed_jwt}</code>.
            </p>

            <p class="mb-4 text-gray-600">
              Please note: all subsequent requests require the above authorisation header.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Content-Type: application/json</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  Specifies that JSON is being sent to the server.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>email</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The email of your ORP account.
                </p>
              </div>
              <hr />
              <div>
                <div class="mt-4 mb-4">
                  <code>password</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The password of your ORP account.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>signed_jwt</code>
                </div>
                <p class="text-sm text-gray-600">
                  Your authentication bearer token.
                </p>
              </div>
            </div>

          </div>



          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.login.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>


            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.login.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <!-- <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Example Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.login.curl" :highlight="highlighter">
                </prism-editor>
              </div>
            </div> -->

          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- Searching -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold" id="searching">Searching</h1>
            <p class="mb-4 text-lg text-primary">
              You can use the Search API to retrieve documents in a flexible and consistent manner.
            </p>

            <p class="mb-4 text-gray-600">
              Searching can be done on a variety of categories.
              For more information, see the <code class="p-1 text-sm text-link bg-secondary">document_metadata_category</code>
              property of the request body.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login endpoint.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Content-Type: application/json</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  Specifies that JSON is being sent to the server.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>filters</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the array of "filter objects" on which to search. These filter objects can be composed to create sophisticated queries.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>operator</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the logical operator indicating how to apply the filter elements.
                  The value here must be <code class="p-1 text-sm text-link bg-secondary">and</code>.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>filter_elements</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the array of objects that describes what category to search, and by what value.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>document_metadata_category</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the category on which to search. The values can be:
                </p>
                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">html</code> -
                  search by the content of the document's HTML.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">title</code> -
                  search by the title of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">longtitle</code> -
                  search by the long title of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">identification</code> -
                  search by the URI of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">enacted</code> -
                  search by when the document was enacted.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">classification</code> -
                  search by the document's classification.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">raw_text</code> -
                  search by the document's Akoma Ntoso representation.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">named_entities</code> -
                  search by the named entities a document references.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">legislation_cited</code> -
                  search by legislation a document cites.
                </p>

              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>websearch_tsquery</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the logical operator indicating how to apply the filter object(s).
                </p>
              </div>

            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>count</code>
                </div>
                <p class="text-sm text-gray-600">
                  The number of documents returned.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>next</code>
                </div>
                <p class="text-sm text-gray-600">
                  The paginated URL to fetch more results.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>previous</code>
                </div>
                <p class="text-sm text-gray-600">
                  The paginated URL of the previous page.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of document objects.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.document_id</code>
                </div>
                <p class="text-sm text-gray-600">
                  The ID of a returned document.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.document_metadata</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of document metadata.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.document_enrichments</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array containing the enrichments added to a document.
                  Types of enrichments are "deontic language extraction", "named entity extraction" and "topic classification".
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.entities</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of objects containing the entities extracted from a document.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.url</code>
                </div>
                <p class="text-sm text-gray-600">
                  The URL to fetch more data relating to the document.
                </p>
              </div>
            </div>
          </div>



          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.searching.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>


            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.searching.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>


        <hr class="mt-12 mb-12" />

        <!-- Graph Search -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold" id="graph_searching">Graph Search</h1>
            <p class="mb-4 text-lg text-primary">
              You can also use the Graph Search API to retrieve nodes and edges which show relationships between legislation data.
            </p>

            <p class="mb-4 text-gray-600">
              Searching can be done on a variety of categories.
              For more information, see the <code class="p-1 text-sm text-link bg-secondary">document_metadata_category</code>
              property of the request body.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login endpoint.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Content-Type: application/json</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  Specifies that JSON is being sent to the server.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>filters</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the array of "filter objects" on which to search. These filter objects can be composed to create sophisticated queries.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>operator</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the logical operator indicating how to apply the filter elements.
                  The value here must be <code class="p-1 text-sm text-link bg-secondary">and</code>.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>filter_elements</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the array of objects that describes what category to search, and by what value.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>document_metadata_category</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the category on which to search. The values can be:
                </p>
                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">html</code> -
                  search by the content of the document's HTML.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">title</code> -
                  search by the title of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">longtitle</code> -
                  search by the long title of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">identification</code> -
                  search by the URI of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">enacted</code> -
                  search by when the document was enacted.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">classification</code> -
                  search by the document's classification.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">raw_text</code> -
                  search by the document's Akoma Ntoso representation.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">named_entities</code> -
                  search by the named entities a document references.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">legislation_cited</code> -
                  search by legislation a document cites.
                </p>

              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>websearch_tsquery</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the logical operator indicating how to apply the filter object(s).
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>relationship_names</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The relationship type between documents to include in the search. The values can be:
                </p>
                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">legislation_cited_in</code> -
                  Legislation cited in other legislation.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">guidance_references_legislation</code> -
                  Legislation cited within guidance.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">same_named_entity</code> -
                  Documents which contain the same named entity.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">same_classification</code> -
                  Documents which have the same classification
                </p>

              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>metadata_categories</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the category on which to search. The values can be:
                </p>
                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">html</code> -
                  search by the content of the document's HTML.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">title</code> -
                  search by the title of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">longtitle</code> -
                  search by the long title of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">identification</code> -
                  search by the URI of the document.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">enacted</code> -
                  search by when the document was enacted.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">classification</code> -
                  search by the document's classification.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">raw_text</code> -
                  search by the document's Akoma Ntoso representation.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">named_entities</code> -
                  search by the named entities a document references.
                </p>

                <p class="mt-4 text-sm leading-7 text-gray-600">
                  <code class="p-1 text-sm text-link bg-secondary">legislation_cited</code> -
                  search by legislation a document cites.
                </p>

              </div>

            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>Edges</code>
                </div>
                <p class="text-sm text-gray-600">
                  The relationships between the nodes.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>edges.data</code>
                </div>
                <p class="text-sm text-gray-600">
                  The details about the relationship.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>edges.data.source</code>
                </div>
                <p class="text-sm text-gray-600">
                  The ID of the source data which has been matched.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>edges.data.target</code>
                </div>
                <p class="text-sm text-gray-600">
                  The ID of the target data which has been matched.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>edges.data.properties</code>
                </div>
                <p class="text-sm text-gray-600">
                  This contains a reference to the target data.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>edges.data.relationship_confirmation</code>
                </div>
                <p class="text-sm text-gray-600">
                  This contains information in regards to whether the relationship has been verified.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>nodes</code>
                </div>
                <p class="text-sm text-gray-600">
                  The documents that the edges relate to.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>nodes.data</code>
                </div>
                <p class="text-sm text-gray-600">
                  Further information on the nodes, such as the Title and Type of the document.
                </p>
              </div>

            </div>
          </div>



          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.graph_searching.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>


            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.graph_searching.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>


        <hr class="mt-12 mb-12" />

        <!-- Enrichments. -->
        <div class="lg:flex">
          <div class="pl-8 pr-8">
            <h1 class="mb-8 text-xl font-bold" id="enrichment">Enrichments</h1>
            <p class="mb-4 text-lg text-primary">
              As part of the Open Regulation Platform, we run various natural language processing (NLP) algorithms
              on the stored documents for the purpose of extracting useful information.
            </p>

            <p class="mb-4 leading-8 text-gray-600">
              We currently have 3 categories of enrichments at the moment. These are
              <code class="p-1 text-sm text-link bg-secondary">deontic language extraction</code>,
              <code class="p-1 text-sm text-link bg-secondary">topic classification</code> and
              <code class="p-1 text-sm text-link bg-secondary">named entity extraction</code>.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">deontic language extraction</code> refers
              to the analysis of a document and the extraction of any pieces of text that may indicate an obligation -
              "shall", "must", "should" etc. This could be useful in getting a quick overview of the obligations outlined by a document.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">topic classification</code> refers
              to the automatic assessment of a document to determine its topic. With the topic of a document extracted,
              users are able to search for documents based on classifications that are relevant to them.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">named entity extraction</code> refers
              to the analysis of a document and the extraction of explicitly named entities. A "named entity"
              might for example be an agency referenced in a document. We can use these extracted named entities
              to start building relationships between the documents. Futhermore, users will also be able to search for documents
              based on the entities they reference.
            </p>

            <p class="mb-4 text-gray-600">
              Please note that these enrichments are largely automatic at the moment, and therefore should
              not be taken as 100% reliable. We currently have a review system in place for the enrichments as we
              aim to improve their accuracy.
            </p>
          </div>
        </div>

        <!-- Subscriptions. -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold" id="subscriptions">Subscriptions</h1>
            <p class="mb-4 text-lg text-primary">
              A user has the option of subscribing to two different types of events: <code class="p-1 text-sm text-link bg-secondary">new document revision</code>
              and <code class="p-1 text-sm text-link bg-secondary">stale document relationship</code>.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">new document revision</code> refers
              to new revisions made to an existing document.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">stale document relationship</code> refers
              to when a legislation -> guidance reference may have become "stale" and thus needs reviewed for validity.
            </p>

            <p class="mb-4 text-gray-600">
              These events are added to a user specific event stream, which can be polled by specific users when an event occurs that matches their subscription.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login endpoint.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Content-Type: application/json</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  Specifies that JSON is being sent to the server.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>event_type_id</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This is the ID of the event type - it will refer to the ID for either <code class="p-1 text-sm text-link bg-secondary">new_document_revision</code> or <code class="p-1 text-sm text-link bg-secondary">stale_document_relationship</code>.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>event_filters</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  This contains the filters for the event subscription.
                </p>
              </div>

            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>event_description</code>
                </div>
                <p class="text-sm text-gray-600">
                  This object contains the details about the event.
                </p>
              </div>
              <hr />

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>event_name</code>
                </div>
                <p class="text-sm text-gray-600">
                  The name of the event.
                </p>
              </div>
              <hr />


            </div>
          </div>



          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">New Document Subscription</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.new_doc_subscriptions.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Stale Document Subscription</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.stale_subscriptions.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Event Stream Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.subscriptions_stream.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Event Stream Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.subscriptions_stream.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- Document overview -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold" id="document">Document Overview</h1>
            <p class="mb-4 text-lg text-primary">
              The document resource is a representation of the legislative and regulatory guidance stored on the platform.
            </p>

            <p class="mb-4 leading-8 text-gray-600">
              A document object is composed primarily of
              <code class="p-1 text-sm text-link bg-secondary">document metadata</code>,
              <code class="p-1 text-sm text-link bg-secondary">document data</code>,
              <code class="p-1 text-sm text-link bg-secondary">related documents</code> and
              <code class="p-1 text-sm text-link bg-secondary">document enrichments</code>.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">document metadata</code> is the object
              describing the document itself. It may include the source, name and date the document was ingested by the platform.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">document data</code> is the entire body of the document.
              This will be in the Akoma Ntoso format.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">related documents</code> refers to a list of other documents that
              are related by taxonomy or content.
            </p>

            <p class="mb-4 text-gray-600">
              <code class="p-1 text-sm text-link bg-secondary">document enrichments</code> refers to information extracted from the document
              by the use of NLP algorithms. For more information refer to the enrichments section.
            </p>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Endpoints</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.documents.endpoints" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- All Documents -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold">All Documents</h1>
            <p class="mb-4 text-lg text-primary">
              This endpoint will return a paginated list of documents along with their basic metadata,
              applied enrichments and extracted entities.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login endpoint.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>count</code>
                </div>
                <p class="text-sm text-gray-600">
                  The number of documents returned.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>next</code>
                </div>
                <p class="text-sm text-gray-600">
                  The paginated URL to fetch more results.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>previous</code>
                </div>
                <p class="text-sm text-gray-600">
                  The paginated URL of the previous page.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of document objects.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.document_id</code>
                </div>
                <p class="text-sm text-gray-600">
                  The ID of a returned document.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.document_metadata</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of document metadata.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.document_enrichments</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array containing the enrichments added to a document.
                  Types of enrichments are "deontic language extraction", "named entity extraction" and "topic classification".
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.entities</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of objects containing the entities extracted from a document.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.url</code>
                </div>
                <p class="text-sm text-gray-600">
                  The URL to fetch more data relating to the document.
                </p>
              </div>
            </div>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.documents.all.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.documents.all.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- Single Document -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold">Single Document</h1>
            <p class="mb-4 text-lg text-primary">
              This endpoint will return a single document object as specified by the ID.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login endpoint.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>document_id</code>
                </div>
                <p class="text-sm text-gray-600">
                  The unique ID of the document.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>document_type</code>
                </div>
                <p class="text-sm text-gray-600">
                  Metadata surrounding the document.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>related_documents</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of objects showing related documents and how they are related.
                  For example, they both reference the same entity.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>reverse_related_documents</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of objects similar to related_documents, except contains all of the documents which
                  cite the current document.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>raw_text</code>
                </div>
                <p class="text-sm text-gray-600">
                  A string that contains the entire document in Akoma Ntoso format.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>document_enrichments</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of objects representing the enrichments extracted from the document.
                  The enrichment object includes the type of enrichment, where it applies etc.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>entities</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of objects representing the entities extracted from the document.
                </p>
              </div>
            </div>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.documents.id.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.documents.id.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>


        <hr class="mt-12 mb-12" />

        <!-- Taxonomy Overview -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold" id="taxonomy">Taxonomy Overview</h1>
            <p class="mb-4 text-lg text-primary">
              The taxonomy represents the hierarchical structure to which a document belongs to.
            </p>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Endpoints</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.taxonomy.endpoints" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- All Taxonomy -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold">All taxonomies</h1>
            <p class="mb-4 text-lg text-primary">
              This endpoint returns a list of taxonomies that are currently on the platform.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login endpoint.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>count</code>
                </div>
                <p class="text-sm text-gray-600">
                  The number of taxonomies returned.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>next</code>
                </div>
                <p class="text-sm text-gray-600">
                  The paginated URL to fetch more results.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>previous</code>
                </div>
                <p class="text-sm text-gray-600">
                  The paginated URL of the previous page.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of taxonomy objects. A taxonomy may contain the name of the taxonomy, an id,
                  a URL that can be used to find more information about a specific taxonomy, and a url that
                  can be used to return a taxonomy's categories.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.id</code>
                </div>
                <p class="text-sm text-gray-600">
                  The ID of a taxonomy object.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.data</code>
                </div>
                <p class="text-sm text-gray-600">
                  The name of a taxonomy object.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.categories</code>
                </div>
                <p class="text-sm text-gray-600">
                  The URL to fetch categories associated with a specific taxonomy.
                </p>
              </div>

              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results.url</code>
                </div>
                <p class="text-sm text-gray-600">
                  The URL to fetch more information about a specific taxonomy.
                </p>
              </div>

            </div>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.taxonomy.all.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.taxonomy.all.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- Single Taxonomy -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold">Single Taxonomy</h1>
            <p class="mb-4 text-lg text-primary">
              This endpoint will return a single taxonomy object as specified by the ID.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login endpoint.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>id</code>
                </div>
                <p class="text-sm text-gray-600">
                  The ID of the taxonomy object.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>data</code>
                </div>
                <p class="text-sm text-gray-600">
                  The name of the taxonomy object.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>categories</code>
                </div>
                <p class="text-sm text-gray-600">
                  The URL to fetch categories associated with a specific taxonomy.
                </p>
              </div>
            </div>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.taxonomy.id.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.taxonomy.id.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>


        <hr class="mt-12 mb-12" />

        <!-- Entity Overview -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold" id="entity">Entity Overview</h1>
            <p class="mb-4 text-lg text-primary">
              An entity referenced noun that has been extracted from the body of a document.
            </p>

            <p class="mb-4 text-gray-600">
              An example of this would be an agency that has been referenced in a document.
            </p>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Endpoints</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.entities.endpoints" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- All Entities -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold">All Entities</h1>
            <p class="mb-4 text-lg text-primary">
              This endpoint returns a paginated list of all the entities extracted from the stored documents.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login endpoint.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>count</code>
                </div>
                <p class="text-sm text-gray-600">
                  The number of entities returned.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>next</code>
                </div>
                <p class="text-sm text-gray-600">
                  The paginated URL to fetch more results.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>previous</code>
                </div>
                <p class="text-sm text-gray-600">
                  The paginated URL of the previous page.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>results</code>
                </div>
                <p class="text-sm text-gray-600">
                  An array of entity objects. An entity may contain the name of the entity, an id,
                  a URL that can be used to find the documents referencing the entity and a URL to
                  fetch the entity itself.
                </p>
              </div>

            </div>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.entities.all.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.entities.all.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <!-- Single Entity -->
        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold">Single Entity</h1>
            <p class="mb-4 text-lg text-primary">
              This endpoint will return a single entity object as specified by the ID.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login request.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>id</code>
                </div>
                <p class="text-sm text-gray-600">
                  The ID of the entity object.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>data</code>
                </div>
                <p class="text-sm text-gray-600">
                  The name of the entity.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>documents</code>
                </div>
                <p class="text-sm text-gray-600">
                  The URL to fetch all documents referencing this entity.
                </p>
              </div>
            </div>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.entities.id.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.entities.id.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>

        <hr class="mt-12 mb-12" />

        <div class="lg:flex">
          <div class="pl-8 pr-8 lg:w-1/2">
            <h1 class="mb-8 text-xl font-bold">Documents By Entity</h1>
            <p class="mb-4 text-lg text-primary">
              This endpoint will return a list of documents that reference an entity
              as specified by the entity ID.
            </p>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Request Headers</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code class="text-sm">Authorization: Bearer {signed_jwt}</code>
                  <span class="float-right ml-4 text-gray-400">Required</span>
                </div>
                <p class="text-sm text-gray-600">
                  The authentication token from the login request.
                </p>
              </div>
            </div>

            <div class="mt-8">
              <h3 class="mb-4 font-bold">Response Body</h3>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>id</code>
                </div>
                <p class="text-sm text-gray-600">
                  The ID of the entity object.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>data</code>
                </div>
                <p class="text-sm text-gray-600">
                  The name of the entity.
                </p>
              </div>
              <hr />
              <div class="mb-4">
                <div class="mt-4 mb-4">
                  <code>documents</code>
                </div>
                <p class="text-sm text-gray-600">
                  The URL to fetch all documents referencing this entity.
                </p>
              </div>
            </div>
          </div>

          <div class="pl-8 pr-8 mt-6 lg:w-1/2 lg:pl-0 lg:pr-0 lg:mt-0">
            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Request</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.entities.documents.request" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>

            <div class="mb-6 rounded-sm bg-tertiary">
              <div class="p-2 bg-secondary">
                <span class="ml-1 text-sm font-bold">Response</span>
              </div>
              <div class="pt-2 pb-2 pl-2 bg-tertiary">
                <prism-editor class="my-editor" readonly v-model="routes.entities.id.response" :highlight="highlighter">
                </prism-editor>
              </div>
            </div>
          </div>
        </div>

        <hr class="mt-12 mb-12" />

      </div>
    </div>

    <div class="w-full bg-primary h-2/12">
    </div>
  </div>
</template>

<script>
  import login from '../json/routes/login.json';
  import document from '../json/routes/document.json';
  import taxonomy from '../json/routes/taxonomy.json';
  import entities from '../json/routes/entities.json';
  import searching from '../json/routes/searching.json';
  import graph_searching from '../json/routes/graph_searching.json';
  import new_doc_subscriptions from '../json/routes/new_doc_subscriptions.json';
  import stale_subscriptions from '../json/routes/stale_subscriptions.json';
  import subscriptions_stream from '../json/routes/subscriptions_stream.json';
  // import Prism Editor
  import { PrismEditor } from 'vue-prism-editor';
  import 'vue-prism-editor/dist/prismeditor.min.css'; // import the styles somewhere

  // import highlighting library (you can use any library you want just return html string)
  import { highlight, languages } from 'prismjs/components/prism-core';
  import 'prismjs/components/prism-json';
  import 'prismjs/themes/prism-coy.css'; // import syntax highlighting styles

  export default {
    components: {
      PrismEditor,
    },
    data: () => ({
      routes: {
        login:  {
          request: login.request + "\n" + JSON.stringify(login.body, null, 2),
          response: JSON.stringify(login.response, null, 2),
          curl: login.curl,
        },
        searching: {
          request: searching.request + "\n" + JSON.stringify(searching.body, null, 2),
          response: JSON.stringify(searching.response, null, 2),
        },
        graph_searching: {
          request: graph_searching.request + "\n" + JSON.stringify(graph_searching.body, null, 2),
          response: JSON.stringify(graph_searching.response, null, 2),
        },
        documents: {
          endpoints: document.endpoints.join("\n"),
          all: {
            ...document.all,
            response: JSON.stringify(document.all.response, null, 2),
          },
          id: {
            ...document.id,
            response: JSON.stringify(document.id.response, null, 2),
          }
        },
        new_doc_subscriptions: {
          request: new_doc_subscriptions.request + "\n" + JSON.stringify(new_doc_subscriptions.body, null, 2),
        },
        stale_subscriptions: {
          request: stale_subscriptions.request + "\n" + JSON.stringify(stale_subscriptions.body, null, 2),
        },
        subscriptions_stream: {
          request: subscriptions_stream.request,
          response: JSON.stringify(subscriptions_stream.response, null, 2),
        },
        taxonomy: {
          endpoints: taxonomy.endpoints.join("\n"),
          all: {
            ...taxonomy.all,
            response: JSON.stringify(taxonomy.all.response, null, 2),
          },
          id: {
            ...taxonomy.id,
            response: JSON.stringify(taxonomy.id.response, null, 2),
          }
        },
        entities: {
          endpoints: entities.endpoints.join("\n"),
          all: {
            ...entities.all,
            response: JSON.stringify(entities.all.response, null, 2),
          },
          id: {
            ...entities.id,
            response: JSON.stringify(entities.id.response, null, 2),
          },
          documents: {
            ...entities.documents,
          }
        }
      },
    }),
    methods: {
      highlighter(code) {
        return highlight(code, languages.json);
      },
    },
  };
</script>

<style>
  .my-editor {
    background: #f7f7f7;
    color: rgb(65, 65, 65);

    font-family: Fira code, Fira Mono, Consolas, Menlo, Courier, monospace;
    font-size: 12px;
    line-height: 1.5;
    padding: 5px;

  }

  .prism-editor__textarea:focus {
    outline: none;
  }

  aside {
    height: fit-content;
  }
</style>