
insert into users (first_name, last_name, password, email) values ('TestUser','1407','NU41SX54!','TestUser1407@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1045','PY51GZ88!','TestUser1045@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1056','GR87DD63!','TestUser1056@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1266','DR64SZ74!','TestUser1266@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1015','NB45RT20!','TestUser1015@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1544','DC16JI83!','TestUser1544@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1685','AM97PO59!','TestUser1685@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1243','SX45EL66!','TestUser1243@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1640','NH38JN17!','TestUser1640@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1576','UX98EH16!','TestUser1576@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1542','YX57TL87!','TestUser1542@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1181','ZI90BK99!','TestUser1181@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1612','RR49BP27!','TestUser1612@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1331','QV49DY35!','TestUser1331@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1312','GZ65HY46!','TestUser1312@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1442','UX17JL52!','TestUser1442@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1781','RA11DR76!','TestUser1781@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1446','BU78YD14!','TestUser1446@beis-orp-alpha.io');
insert into users (first_name, last_name, password, email) values ('TestUser','1453','YO27OP66!','TestUser1453@beis-orp-alpha.io');

insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1407@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1045@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1056@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1266@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1015@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1544@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1685@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1243@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1640@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1576@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1542@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1181@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1612@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1331@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1312@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1442@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1781@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1446@beis-orp-alpha.io'),(select id from role where name = 'editor'));
insert into user_role (user_id,role_id) values ((select id from users where email = 'TestUser1453@beis-orp-alpha.io'),(select id from role where name = 'editor'));